In [1]:
import pandas as pd
import pandera as pa    # para usar SCHEMAs. Se essa biblioteca não estiver instalada: pip install pandera

O comando "read" vai ler o arquivo csv e criar uma dataframe (tabela). Teremos que alterar o separador default (vírgula) pelo (;). Mostra as primeiras 5 linhas (0 a 4) e as últimas 5 (6009 a 6113)

Conforme as necessidades de alteração da tabela, acrescentamos novos parâmetros ao comando, nessa sequência:
df = pd.read_csv('ocorrencia.csv')
df = pd.read_csv('ocorrencia.csv', sep=';')
df.dtypes       # tipo de dados
Temos que alterar os campos ocorrencia_dia e data pois não estão como tipo data:
df = pd.read_csv('ocorrencia.csv', sep=';', parse_dates=['ocorrencia_dia'])
df = pd.read_csv('ocorrencia.csv', sep=';', parse_dates=['ocorrencia_dia'], dayfirst=True)
Cuidado: Se houver uma data inválida, o comando acima não vai funcionar
Quando a célula de data está vazia, mostra "Nat", se for texto, mostra 'NaN'

df.head(10)  --> lista os 10 primeiros itens
df.tail(10)  --> lista os 10 últimos itens
df.ocorrencia_dia.dt.month      # separamos apenas o mês
esquema = pa.DataFrameSchema(  columns = { 'codigo_ocorrencia':pa.Column(pa.Int)     })
esquema.validate(df)     # valida e mostra a tabela esquema (schema)

- No campo 'ocorrencia_hora', utilizaremos uma expressã regular para formatar a hora. Ela checa se os primeiros dígitos estão até 23h e ambos os próximos (min e seg) até 59: pa.Check.str_matches(r'^([0-1]?[0-9]|[2][0-3]):([0-5][0-9])(:[0-5][0-9])?$')
- No campo 'ocorrencia_uf', para limitar a coluna a 2 dígitos, usaremos a expressão: pa.Check.str_length(2,2)

df.set_index('codigo_ocorrencia', )  # Se quiser alterar o índice do Data Frame (tabela). Isso só testa. precisa incrementar:
df.set_index('codigo_ocorrencia', inplace=True )     # agora o indice default não funciona mais, só o novo.
df.reset_index(drop=True, inplace=True)              # volta ao índice original

CONSULTA:
    df             # lista todo o dataframe
    df.loc[3]      # mostra o conteúdo de toda a linha 3
    df.loc[7:10]   # lista as linhas de 7 até 10
    df.loc[1,'ocorrencia_cidade']   # mostra o conteúdo da célula [linha, Coluna] = "BELEM"
    df.loc[[10,40]]  # mostra as linhas 10 e 40
    df.loc[df.ocorrencia_cidade=='ATIBAIA']  # lista todas as cidades = "ATIBAIA"
    df.isna()    # mostra toda a tabela com False, e True onde há um "NA"     ou       df.isnull()
    df.isna().sum()     # mostra o total de valores "NA" por coluna    ou     df.isnull().sum() 
    
    
    
    
ALTERAÇÃO:
    df.loc[0,'ocorrencia_aerodromo'] = ''  # faz a 1ª célula do campo "ocorrencia_aerodromo" = vazio
    df.loc[1] = 20  # todos os campos da "linha 1" = 20
    df.loc[:, 'total_recomendacoes']=10 # toda a coluna "total_recomendacoes" = 10
    df['ocorrencia_uf_bkp'] = df.ocorrencia_uf # cria uma nova coluna copiando (como backup)
    df.loc[df.ocorrencia_uf=='SP', ['ocorrencia_classificacao']] = 'GRAVE'  # altera todas as classificações em SP para "GRAVE"
    df.loc[df.ocorrencia_aerodromo=='****', ['ocorrencia_aerodromo']] = pd.NA   # substitui "****" por "NA" (Not Available) 
    df.replace(['**','###!','####','****','*****','NULL'], pd.NA, inplace=True)   # faz as modificações tudo de uma vez
    df.fillna(0)     # troca todos os valores "NA" por 0
    df.replace([0], pd.NA, inplace=True)    # troca todos os 0 por "NA"  e Salva (inplace=True).
    df.fillna(value = {'total_recomendacoes':10}, inplace=True)     # troca 0 por 10 apenas no campo indicado
    df.drop(['total_recomendacoes_B'], axis=1, inplace=True)   # axis=0 (linha, que é o default)   axis=1 (coluna)
    df.dropna()    # exclui todas as linhas que tem valores não informados (só não apagou pois não colocamos o "inplace=True")
    df.dropna(subset=['ocorrencia_uf'])  # apaga apenas os valores "NA" da coluna indicada.  
    df.drop_duplicates()   # exclui as linhas duplicadas

In [18]:
df = pd.read_csv('ocorrencia.csv', sep=';', parse_dates=['ocorrencia_dia'], dayfirst=True)
df.head(10)    # mostra os 10 primeiros itens do dataframe df

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,****,2010-01-03,12:00:00,0
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,****,2010-01-04,17:30:00,0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
5,39807,39807,INCIDENTE,SALVADOR,BA,****,2010-01-06,17:53:00,0
6,40215,40215,INCIDENTE,COARI,AM,SBUY,2010-01-07,18:40:00,0
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,****,2010-01-09,12:30:00,3
8,39156,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2
9,39711,39711,INCIDENTE GRAVE,PARÁ DE MINAS,MG,****,2010-01-10,20:00:00,0

Vamos criar um schema com uma coluna chamada 'codigo_ocorrencia' tipo inteira:

In [19]:
esquema = pa.DataFrameSchema( columns = { 
    'codigo':pa.Column(pa.Int, required=False),  # se às vezes tem essa coluna, é só alterar para = True
    'codigo_ocorrencia':pa.Column(pa.Int),  
    'codigo_ocorrencia2':pa.Column(pa.Int),
    'ocorrencia_classificacao': pa.Column(pa.String),
    'ocorrencia_cidade': pa.Column(pa.String),
    'ocorrencia_uf': pa.Column(pa.String, pa.Check.str_length(2,2)),
    'ocorrencia_aerodromo': pa.Column(pa.String),
    'ocorrencia_dia': pa.Column(pa.DateTime),
    'ocorrencia_hora': pa.Column(pa.String, pa.Check.str_matches(r'^([0-1]?[0-9]|[2][0-3]):([0-5][0-9])(:[0-5][0-9])?$'),nullable=True),
    'total_recomendacoes': pa.Column(pa.Int)       
})

In [20]:
esquema.validate(df)     # valida e mostra a tabela esquema (schema)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,****,2010-01-03,12:00:00,0
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,****,2010-01-04,17:30:00,0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
...,...,...,...,...,...,...,...,...,...
6109,80245,80245,INCIDENTE,RECIFE,PE,SBRF,2021-08-15,15:05:00,0
6110,80247,80247,INCIDENTE,PORTO VELHO,RO,SBPV,2021-08-16,02:30:00,0
6111,80251,80251,INCIDENTE,BELÉM,PA,SBBE,2021-08-17,15:45:00,0
6112,80257,80257,ACIDENTE,DOM AQUINO,MT,****,2021-08-18,16:00:00,0
6113,80259,80259,INCIDENTE,CAMPINAS,SP,SBKP,2021-08-18,12:45:00,0